// Generated by scripts/crop-scenery.py; original dimensions preserve world scale.
export const sceneryCrops = [
  { width: 1920, height: 1072, top: 328, croppedHeight: 463 },
  { width: 1920, height: 1072, top: 510, croppedHeight: 538 },
  { width: 2752, height: 1536, top: 404, croppedHeight: 1132 },
  { width: 1920, height: 1072, top: 673, croppedHeight: 301 },
  { width: 2752, height: 1536, top: 1174, croppedHeight: 362 },
] as const;
