"""Crop fully transparent rows from active Jungle Journey scenery tiles.

Requires Pillow. Source files stay intact; generated files use quality 80 WebP.
"""

from pathlib import Path
from PIL import Image, ImageChops

SOURCE = Path(__file__).resolve().parents[1] / "src/assets/jungle/web"
METADATA = Path(__file__).resolve().parents[1] / "src/components/sceneryCrops.ts"
NAMES = ("l1_mountain", "l2_green", "l3_trees", "l4_road", "l5_foreground_blurred")
rows = []

for name in NAMES:
    original = Image.open(SOURCE / f"{name}.webp").convert("RGBA")
    bounds = original.getchannel("A").getbbox()
    if bounds is None:
        raise ValueError(f"{name}: empty tile")
    if bounds[0] != 0 or bounds[2] != original.width:
        raise ValueError(f"{name}: horizontal crop would change the repeat period")
    # Preserve transparent neighbor rows for bilinear filtering at the edge.
    bounds = (0, max(0, bounds[1] - 2), original.width, min(original.height, bounds[3] + 2))
    cropped = original.crop(bounds)
    output = SOURCE / f"{name}_cropped.webp"
    cropped.save(output, format="WEBP", quality=80, method=6, exact=True)
    decoded = Image.open(output).convert("RGBA")
    if ImageChops.difference(cropped.getchannel("A"), decoded.getchannel("A")).getbbox() is not None:
        raise ValueError(f"{name}: decoded alpha differs from the source")
    rows.append(f"  {{ width: {original.width}, height: {original.height}, top: {bounds[1]}, croppedHeight: {cropped.height} }},")
    print(f"{name}: {original.size} -> {cropped.size}, top={bounds[1]}")

METADATA.write_text(
    "// Generated by scripts/crop-scenery.py; original dimensions preserve world scale.\n"
    "export const sceneryCrops = [\n" + "\n".join(rows) + "\n] as const;\n",
    encoding="utf-8",
)
